---
Database:
  DBName: d_blog
  Password: root
  Username: root
Server:
  MaxPageSize: 30
  Mode: debug
  PageSize: 10
  Port: ':8081'
JWT:
  Secret: asd39Xasd1OS
  Issuer: blog-service
  Expire: 7200